# Generated by Django 3.2.7 on 2021-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='s_mean_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
