# Generated by Django 3.2.7 on 2021-11-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('name', 'class_teacher')},
        ),
    ]
