# Generated by Django 3.2.7 on 2021-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kcpe_marks',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
