# Generated by Django 3.2.7 on 2021-10-25 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='endterm',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(70), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='results',
            name='exam1',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='results',
            name='exam2',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
    ]
