# Generated by Django 3.2.7 on 2021-10-20 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='staff_number',
        ),
    ]
