# Generated by Django 3.2.7 on 2021-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_kcpe_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
