# Generated by Django 3.2.7 on 2021-11-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20211028_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
