# Generated by Django 3.2.7 on 2021-10-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_number',
            field=models.CharField(max_length=2000),
        ),
    ]
