# Generated by Django 3.2.7 on 2021-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_classes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(on_delete=models.SET('NoNe'), to='school.teacher', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('name', 'year')},
        ),
    ]
