# Generated by Django 3.2.7 on 2021-11-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_results_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='p_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='t_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
