# Generated by Django 3.2.7 on 2021-10-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20211002_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(choices=[('Form One Term One', 'Form One Term One'), ('Form One Term Two', 'Form One Term Two'), ('Form One Term Three', 'Form One Term Three'), ('Form Two Term One', 'Form Two Term One'), ('Form Two Term Two', 'Form Two Term Two'), ('Form Two Term Three', 'Form Two Term Three'), ('Form Three Term One', 'Form Three Term One'), ('Form Three Term Two', 'Form Three Term Two'), ('Form Three Term Three', 'Form Three Term Three'), ('Form Four Term One', 'Form Four Term One'), ('Form Four Term Two', 'Form Four Term Two'), ('Form Four Term Three', 'Form Four Term Three')], max_length=1000),
        ),
    ]
