# Generated by Django 3.2.7 on 2021-11-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20211109_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='p_comments',
        ),
        migrations.RemoveField(
            model_name='results',
            name='t_comments',
        ),
        migrations.AddField(
            model_name='report',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.classes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='p_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='t_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('classes', 'student')},
        ),
    ]
