# Generated by Django 3.2.7 on 2021-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20211004_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subjects',
            name='classes',
            field=models.ManyToManyField(to='school.Classes'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='school.Subjects'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Profiles/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Profiles/'),
        ),
    ]
