# Generated by Django 3.2.7 on 2021-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_classes_is_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Students', models.ManyToManyField(to='school.Student')),
                ('classes', models.ForeignKey(on_delete=models.SET('NoNe'), to='school.classes')),
            ],
        ),
    ]
