# Generated by Django 3.2.7 on 2021-10-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='staff_number',
            field=models.CharField(max_length=2000),
        ),
    ]
