# Generated by Django 3.2.7 on 2021-11-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_report_all_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='all_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
