# Generated by Django 3.2.7 on 2021-11-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20211111_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(default=1, on_delete=models.SET('NoNe'), to='school.teacher'),
            preserve_default=False,
        ),
    ]
