# Generated by Django 3.2.7 on 2021-10-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_classes_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='id',
        ),
        migrations.AlterField(
            model_name='results',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='school.subjects'),
        ),
    ]
