# Generated by Django 3.2.7 on 2021-11-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_storeclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreClass',
            new_name='classRecord',
        ),
    ]
