# Generated by Django 3.2.7 on 2021-11-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_subjectinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectinfo',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.classes'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subjectinfo',
            unique_together={('student', 'classes')},
        ),
        migrations.RemoveField(
            model_name='subjectinfo',
            name='subject',
        ),
    ]
