# Generated by Django 3.2.7 on 2021-11-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_rename_storeclass_classrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrecord',
            old_name='Students',
            new_name='students',
        ),
    ]
