# Generated by Django 3.2.7 on 2021-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_classes_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('openingDate', models.DateField(blank=True, null=True)),
                ('closingDate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
