# Generated by Django 3.2.7 on 2021-10-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_results_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeadTeacher',
            new_name='Principal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_headteacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('student', 'Student'), ('principal', 'principal')], max_length=20, null=True),
        ),
    ]
