# Generated by Django 3.2.7 on 2021-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
