# Generated by Django 3.2.7 on 2021-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_students_classrecord_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecord',
            name='class_teacher',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
