# Generated by Django 3.2.7 on 2021-11-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_classrecord_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=models.SET('NoNe'), to='school.teacher', unique=True),
        ),
    ]
