# Generated by Django 3.2.7 on 2021-11-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20211116_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_report', to='school.classes'),
        ),
        migrations.AlterField(
            model_name='report',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report', to='school.student'),
        ),
    ]
