# Generated by Django 3.2.7 on 2021-12-04 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_timetable_timetableitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.classes', unique=True),
        ),
    ]
