# Generated by Django 3.2.7 on 2021-12-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_timetable_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableitems',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetableitems',
            name='timetable',
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
        migrations.DeleteModel(
            name='TimeTableItems',
        ),
    ]
